### ISSUE TITLE
Binaries from R container

### ISSUE THREAD

**Issue by grantmcdermott** [LOST-STATS/docker-images#1]
This is all great stuff, Kevin. As discussed over at the related [LOST thread](https://github.com/LOST-STATS/lost-stats.github.io/pull/64#issuecomment-719347589), we should be able to greatly reduce the R container build times by switching to an image that pulls in pre-compiled R package binaries for Linux; as opposed to building everything from source. 

(Disclaimer: Existing build times aside, I'm pretty sure that this isn't the case if I quickly look at the current Dockerfile. Bit I'm rushing while kiddo no. 2 is sleeping...)

We have two options:

1) Continue with **renv**, but switch to an image that automatically pulls in the pre-built binaries that are hosted at RStudio's package manager ([**RSPM**](https://packagemanager.rstudio.com/)), i.e. as opposed to one of the regular CRAN mirrors. The easiest way to do this is to build off the [versioned stack](https://github.com/rocker-org/rocker#versioned-stack-builds-on-r-ver) images from the Rocker project. See example [here](https://medium.com/@skyetetra/r-docker-faster-28e13a6d241d), while I talk specifically about the **renv**+RSPM workflow [here](https://github.com/grantmcdermott/renv-rspm). Considerations:
   - The RSPM binaries only include compiled package code. They don't check that system deps are met, although the Rocker images already pull in the most commonly required ones. We'd have to specify any others in the Dockerfile.

2) Alternatively, we skip **renv** altogether and go the [**BSPM**](http://dirk.eddelbuettel.com/blog/2020/08/26/#029_introducing_bspm) route. The way that BSPM works is that it uses an alternate source of compiled R package binaries &mdash; Michael Rutter's PPA in the case of Ubuntu &mdash; but it also pulls in the relevant system dependencies at the same time. Dirk's got a v. nice introduction at the previous link and there's also a base container ready to go. Considerations:
   - Unlike with an **renv** lockfile (which captures the version of a specific package), the BSPM approach will always install the *latest* version of said package. This might well be the way we want to go anyway &mdash; good way to check that our LOST guides are up-to-date &mdash; but I wanted to flag nonetheless.

Personally, I'm leaning towards to option 2. But happy to discuss and clarify as needed!

**Comment by khwilson** [comment]
A hah! This explanation reveals why I couldn't get RSPM to work no matter how hard I tried: It doesn't work with debian. Doh. Well, that explains that. :-) I've now fixed that in this build: https://github.com/LOST-STATS/docker-images/runs/1337237835?check_suite_focus=true .

Notably, this image is now more or less rocker's rspm image, so my vote is to move to that going forward. For completeness, though, the one downside of moving is that it is often hard to find the list of dependencies for any given package or code snippet, so in the spirit of an "all in one place for code snippets," it may make sense to keep it here.

As to the choice between 1 vs 2, as a matter of principle, I'm generally _against_ automatically using the latest of anything. I also think that it makes a lot of sense to use these repositories not just as examples of statistical techniques, but also how to build repeatable analyses. From that perspective, I think it makes more sense to stick with the renv/lockfile philosophy.

Notably, there might actually be a way to combine both! Specifically, I haven't tried it out, but I don't think that Rutter's PPA actually replaces any Ubuntu-hosted packages, and per the Ubuntu LTS philosophy, those packages won't be changing (except for security updates) for the next several years. This would mean that we could adopt the following strategy:
  * Use BSPM as the package installer
  * Run `renv::snapshot()` for posterity
  * Have Github Actions rebuild the image (say) every month and automatically submit a PR for our review that bumps all the versions and runs all the tests.

Perhaps that's the way to go?

**Comment by grantmcdermott** [comment]
Sorry, I should have specified the Debian vs Ubuntu thing at the outset. You're exactly right, though.

> As to the choice between 1 vs 2, as a matter of principle, I'm generally against automatically using the latest of anything. I also think that it makes a lot of sense to use these repositories not just as examples of statistical techniques, but also how to build repeatable analyses. From that perspective, I think it makes more sense to stick with the renv/lockfile philosophy.

Cool cool. 

> Perhaps that's the way to go?

Yours is a neat solution. I've been thinking of another solution that might be simpler: RSPM actually tells you which system dependencies are required for a given package (on your OS). E.g. For the Cairo package [it tells us](https://packagemanager.rstudio.com/client/#/repos/1/packages/Cairo) that we need `sudo apt-get install -y libcairo2-dev` on Ubuntu 20.04. We should be, in principle be able to extract all of these sys deps from the RSPM API and install those at build time...

**UPDATE:** Should have checked before typing, because it looks like the RStudio folks have already packaged something that does exactly this! https://github.com/rstudio/r-system-requirements In fact, you can run it through `remotes::system_requirements` (TIL...)

**Comment by khwilson** [comment]
Super cool!

See #2 for a little script that converts a renv.lock into the system requirements. Not sure exactly how they should be incorporated, but it definitely seems to work!

**Comment by grantmcdermott** [comment]
Alongside my other comment at #2 I think we should be able close this now, right?

**Comment by khwilson** [comment]
Yep! Binaries work!
